# Testing of Soneira-Peebles algorithm

In [38]:
# imports
from pyigm.fN import clustering as pycl

In [47]:
reload(pycl)
pycl.sp_cluster(2, 1., 4, 4., 2)

--Return--
> /Users/xavier/local/Python/pyigm/pyigm/fN/clustering.py(101)sp_cluster()->None
-> pdb.set_trace()
(Pdb) sp_dict
{0: [{'pos': array([ 0.,  0.]), 'parent': 0, 'level': 0}], 1: [{'idx': 0, 'pos': array([ 0.21480805, -0.09181222]), 'parent': 0, 'level': 1}, {'idx': 1, 'pos': array([-0.15804059, -0.14771986]), 'parent': 0, 'level': 1}, {'idx': 2, 'pos': array([ 0.03386251,  0.04777235]), 'parent': 0, 'level': 1}, {'idx': 3, 'pos': array([ 0.23225726,  0.07658855]), 'parent': 0, 'level': 1}], 2: [{'idx': 0, 'pos': array([ 0.27047953, -0.08765819]), 'parent': 0, 'level': 2}, {'idx': 1, 'pos': array([ 0.18386962, -0.06420447]), 'parent': 0, 'level': 2}, {'idx': 2, 'pos': array([ 0.19823789, -0.09198117]), 'parent': 0, 'level': 2}, {'idx': 3, 'pos': array([ 0.18062993, -0.11011652]), 'parent': 0, 'level': 2}, {'idx': 4, 'pos': array([-0.13918412, -0.17110325]), 'parent': 1, 'level': 2}, {'idx': 5, 'pos': array([-0.12444866, -0.11249022]), 'parent': 1, 'level': 2}, {'idx': 6, 'pos':

BdbQuit: 

## Tests

In [ ]:
# Random state
seed = 12345
rstate = np.random.RandomState(seed)

In [14]:
tmp2 = [100,100]
tmp = rstate.rand(*tmp2)

In [15]:
tmp.shape

(100, 100)

In [9]:
tmp

array([[ 0.92961609,  0.31637555,  0.18391881, ...,  0.82638043,
         0.89810064,  0.0427153 ],
       [ 0.195795  ,  0.29450132,  0.62699988, ...,  0.4568695 ,
         0.24992692,  0.56828356],
       [ 0.846943  ,  0.37809954,  0.43246512, ...,  0.50732721,
         0.4930667 ,  0.18687476],
       ..., 
       [ 0.44885823,  0.02490455,  0.73755915, ...,  0.83907071,
         0.94822204,  0.04176738],
       [ 0.5024281 ,  0.93071366,  0.13587403, ...,  0.39744439,
         0.12687514,  0.11179089],
       [ 0.12389262,  0.51428738,  0.57087713, ...,  0.01906542,
         0.25946199,  0.76037777]])

In [19]:
ncenter = 3
ndim = 3

In [29]:
buff = 10*ncenter

In [30]:
args = [buff,ndim]

In [31]:
randxy = rstate.rand(*args)
randxy.shape

(30, 3)

In [32]:
radii2 = np.sum(randxy**2,1)
radii2

array([ 1.30211786,  0.66369708,  0.88356597,  0.86647619,  0.733028  ,
        0.4099033 ,  1.57211796,  1.25079686,  1.0029769 ,  1.28029237,
        0.91119781,  0.73895817,  0.95613006,  0.85939391,  1.36543329,
        0.56889893,  1.43187572,  1.01532774,  0.57118495,  1.10367217,
        1.1667784 ,  1.05904114,  1.32119917,  1.83099026,  1.026507  ,
        1.07471315,  0.92098797,  1.14276252,  0.05238159,  0.78763021])

In [33]:
gdr2 = np.where(radii2 < 1.)[0]

In [34]:
tmp = randxy[gdr2[0:ncenter],:]

In [35]:
tmp

array([[ 0.39317501,  0.39040918,  0.59723627],
       [ 0.51930028,  0.55877466,  0.54923954],
       [ 0.84798604,  0.27232858,  0.27061598]])

In [36]:
tmp.shape

(3, 3)

In [37]:
    sp_dict = {0:[0,0]}
    