# Ingesting Prochaska+11 CGM dataset [v1.0]

In [2]:
# imports
from astropy.table import Table
from astropy.coordinates import SkyCoord

import pyigm
from pyigm.cgm.cgmsurvey import CGMAbsSurvey

## Summary

In [2]:
ovi_file = pyigm.__path__[0]+'/data/CGM/P11/lowovidat.fits'

In [3]:
ovidat = Table.read(ovi_file)

In [4]:
ovidat[0:3]

<Table length=3>
      QSO       ...
     str15      ...
--------------- ...
Q0026+1259      ...
TONS180         ...
TONS210         ...

In [5]:
qso_radec = SkyCoord(ra=ovidat['QSO_RA'], dec=ovidat['QSO_DEC'], unit=(u.hourangle, u.deg))

## Dwarfs

In [6]:
cgm_dwarf_file = pyigm.__path__[0]+'/data/CGM/P11/dwarf_galabs_strct.fits'

In [7]:
cgm_dwarfs = Table.read(cgm_dwarf_file)

In [8]:
cgm_dwarfs[0:3]

<Table length=3>
   FIELD      ID  OBJ_ID ...      DRA            DDEC     
   str11    int32  str1  ...    float64        float64    
----------- ----- ------ ... ------------- ---------------
Q0026+1259   1303      a ... 45.6990947951 0.0191390593786
TONS180      2295      a ...  154.07390626 0.0207054292147
PKS0405-123 90033      a ... 97.7760719383 0.0877822129587

### Funny columns -- Renaming

In [9]:
cgm_dwarfs.rename_column('DRA', 'rho(kpc)')
cgm_dwarfs.rename_column('DDEC', 'L(L*)')

#### MAG has HI
    2 == Ref
    3 == z
    4 == Lya EW
    5 == sigEW Lya
    8 == NHI
    9 == sigNHI

In [10]:
cgm_dwarfs[1]['MAG']

array([  1.89230003e+01,   1.80701466e+01,   5.00000000e+00,
         2.34109219e-02,   2.22000000e+02,   2.90000000e+01,
         5.60000000e+01,   4.00000000e+00,   1.38000002e+01,
         1.00000000e+00], dtype=float32)

#### MAGERR has OVI
    2 == Ref
    3 == z
    4 == EW 1031
    5 == sigEW 1031
    8 == NOVI    
    9 == sigNOVI

In [11]:
cgm_dwarfs[1]['MAGERR']

array([  8.79999995e-02,   6.49999976e-02,   4.00000000e+00,
         2.33999994e-02,   4.30000000e+01,   1.50000000e+01,
         3.00000000e+01,   0.00000000e+00,   1.34799995e+01,
         5.00000007e-02], dtype=float32)

#### Refs

In [12]:
refdict = {1: 'tripp08', 2: 'tc08a', 3: 'ds08', 4: 'dsr+06', 5: 'pss04', 6: 'cm09', 9: 'p+11'}

## Ingest
    python ingest_lit.py

## Read

In [3]:
p11_tarfile = pyigm.__path__[0]+'/data/CGM/P11/P11_sys.tar'

In [4]:
p11 = CGMAbsSurvey.from_tarball(p11_tarfile, chk_lowz=False)

/Users/xavier/local/Python/linetools/linetools/lists/linelist.py:374: RuntimeWarning: divide by zero encountered in log10
  self._data['log(w*f)'] = np.log10(qm_strength)
/Users/xavier/anaconda/lib/python2.7/site-packages/numpy/ma/core.py:824: RuntimeWarning: invalid value encountered in less_equal
  return umath.less_equal(x, self.critical_value)


Loading abundances from Asplund2009
Abundances are relative by number on a logarithmic scale with H=12
Skipping a likely folder: CGM_JSON


/Users/xavier/local/Python/linetools/linetools/isgm/abssystem.py:288: UserWarning: Input AbsComponent with Zion=(8, 6) does not match AbsSystem rules. Not appending
  warnings.warn('Input AbsComponent with Zion={} does not match AbsSystem rules. Not appending'.format(abscomp.Zion))
/Users/xavier/local/Python/linetools/linetools/isgm/abssystem.py:294: UserWarning: Failed velocity overlap
  warnings.warn('Failed velocity overlap')
/Users/xavier/local/Python/linetools/linetools/isgm/abssystem.py:288: UserWarning: Input AbsComponent with Zion=(1, 1) does not match AbsSystem rules. Not appending
  warnings.warn('Input AbsComponent with Zion={} does not match AbsSystem rules. Not appending'.format(abscomp.Zion))


In [5]:
p11

<CGM_Survey:  nsys=54, ref=>
<IGMSystem: IGMSystem 00:29:13.8 13:16:04, 0.0329451, NHI=0, Z/H=0>
<IGMSystem: IGMSystem 00:29:13.8 13:16:04, 0.039311, NHI=0, Z/H=0>
<IGMSystem: IGMSystem 00:57:20 -22:22:56, 0.0233644, NHI=13.8, Z/H=0>
<IGMSystem: IGMSystem 00:57:20 -22:22:56, 0.045619, NHI=13.8, Z/H=0>
<IGMSystem: IGMSystem 03:11:55.2 -76:51:51, 0.202643, NHI=15.14, Z/H=0>
<IGMSystem: IGMSystem 03:11:55.2 -76:51:51, 0.0593531, NHI=13.53, Z/H=0>
<IGMSystem: IGMSystem 04:07:48.4 -12:11:37, 0.0964516, NHI=14.64, Z/H=0>
<IGMSystem: IGMSystem 04:07:48.4 -12:11:37, 0.297609, NHI=13.85, Z/H=0>
<IGMSystem: IGMSystem 04:07:48.4 -12:11:37, 0.352, NHI=14.04, Z/H=0>
<IGMSystem: IGMSystem 04:07:48.4 -12:11:37, 0.153212, NHI=13.46, Z/H=0>
<IGMSystem: IGMSystem 04:07:48.4 -12:11:37, 0.203022, NHI=13, Z/H=0>
<IGMSystem: IGMSystem 04:07:48.4 -12:11:37, 0.36124, NHI=15.14, Z/H=0>
<IGMSystem: IGMSystem 04:07:48.4 -12:11:37, 0.167, NHI=15.47, Z/H=0>
<IGMSystem: IGMSystem 04:07:48.4 -12:11:37, 0.167043, NHI

In [6]:
p11.rho

<Quantity [  46.32007042, 231.08717107, 153.91919088, 281.05023842,
             34.78581646, 241.08235808, 271.56656557, 263.85542101,
            170.30403727, 193.11905036, 277.85573984, 228.92416305,
            101.21597012, 122.33510368, 181.21741485,  78.67047199,
            306.79467169, 159.32049028, 133.01256117, 221.58366503,
            137.97841172, 151.94838708,  72.60291124, 182.78669925,
            138.10197377,  94.40182666, 106.07146536,  92.90730056,
             37.14686961,  85.54748551,  41.25864481, 260.27253479,
            120.93128195, 243.45856691, 225.98146589,  69.86583806,
            227.78876094,  88.46379097,  99.49390855, 274.8521744 ,
            162.60742332, 309.02130732, 176.70156002, 282.59706888,
            293.98085988, 184.38541882, 228.32783121, 305.40178171,
            266.93146969, 292.71386558, 236.98360734,  35.06117805,
            271.77462491, 108.99879108] kpc>

In [7]:
p11.NHI

array([  0.        ,   0.        ,  13.80000019,  13.80000019,
        15.14000034,  13.52999973,  14.64000034,  13.85000038,
        14.03999996,  13.46000004,  13.        ,  15.14000034,
        15.47000027,  15.47000027,   0.        ,  13.89999962,
        14.        ,  14.43000031,  13.64000034,  13.64000034,
        14.35000038,  15.72999954,  15.72999954,  15.67000008,
        15.67000008,  14.77999973,  13.93999958,  19.29999924,
        13.10000038,  15.38000011,   0.        ,   0.        ,
         0.        ,   0.        ,  15.01000023,  15.35000038,
        14.82999992,  15.28999996,   0.        ,   0.        ,
        13.10000038,  13.67000008,   0.        ,   0.        ,
         0.        ,   0.        ,  14.30000019,  14.07999992,
        13.06000042,  15.10999966,  14.28999996,  15.10999966,
        14.07999992,  13.56000042])