# Demo retrieving data from Cloudy grid

In [1]:
import numpy as np
import pickle
import h5py
from pyigm.metallicity.getionisation import init_interpolator


In [3]:
##Interpolate the Cloudy grid
grid='/Users/wotta/Dropbox/Research/COS-CGM-Legacy/Strong_LLSs/Cloudy/Cloudy_grids/grid_cgm_extensive_HM05_carbalpha.pkl'
interp=init_interpolator(grid)


Loading Cloudy grid...
...Done


In [8]:
##Define a set of grid positions at which we want to back-calculate the properties
##Note: these need to correspond to the correct axes in the grid file

##For now, we'll load in a set of MCMC output walkers
filelist = '/Users/wotta/Dropbox/Research/COS-CGM-Legacy/Strong_LLSs/Results/MCMC_output/W17-master/2MASS-J09512393+3542490_z0.33778600_emcee.pkl'
from MCMC_output import MCMC_output
mcmc = MCMC_output(infiles=filelist, quantity=None)
walkers, nsys, limit_code = mcmc.get_walkers()

In [11]:
len(walkers), len(walkers[0]), walkers[0]

(100000,
 5,
 array([ 17.63207537,   0.33779389,  -1.04721451,  -2.5066232 ,   0.01799628]))

In [12]:
interp.keys()

['temperature', 'SiII', 'SiIII', 'HI', 'CIV', 'CIII', 'CII']

In [13]:
xSiII = interp['SiII'](walkers)

In [14]:
len(xSiII)

100000

In [15]:
print(xSiII[0:20])

[-0.849991   -0.849991   -0.849991   -0.86690213 -0.85750394 -0.8929576
 -0.8929576  -0.87936978 -0.90276939 -0.88269155 -0.88269155 -0.88269155
 -0.89577626 -0.89577626 -0.89577626 -0.89577626 -0.97468177 -0.8642196
 -0.86552073 -0.89641725]


In [16]:
print(walkers[0])

[ 17.63207537   0.33779389  -1.04721451  -2.5066232    0.01799628]


In [17]:
xCIV = interp['CIV']([14.5,0.1,-0.3,-4.5,0.0])

In [18]:
xCIV

array([-0.66568])

In [19]:
cols = np.arange(13.5,15,0.1)
zs = np.array([0.05,0.1,0.15])
metals = np.array([-1,-0.5,0])
nH =np.arange(-4.5,-1,0.3)
carb = np.zeros(1)

In [26]:
gm = np.meshgrid(cols,zs,metals,nH,carb)

In [27]:
np.shape(gm)

(5, 3, 15, 3, 12, 1)

In [28]:
gm = np.array(gm)
gm.T

array([[[[[[ 13.5 ,   0.05,  -1.  ,  -4.5 ,   0.  ],
           [ 13.5 ,   0.1 ,  -1.  ,  -4.5 ,   0.  ],
           [ 13.5 ,   0.15,  -1.  ,  -4.5 ,   0.  ]],

          [[ 13.6 ,   0.05,  -1.  ,  -4.5 ,   0.  ],
           [ 13.6 ,   0.1 ,  -1.  ,  -4.5 ,   0.  ],
           [ 13.6 ,   0.15,  -1.  ,  -4.5 ,   0.  ]],

          [[ 13.7 ,   0.05,  -1.  ,  -4.5 ,   0.  ],
           [ 13.7 ,   0.1 ,  -1.  ,  -4.5 ,   0.  ],
           [ 13.7 ,   0.15,  -1.  ,  -4.5 ,   0.  ]],

          ..., 
          [[ 14.7 ,   0.05,  -1.  ,  -4.5 ,   0.  ],
           [ 14.7 ,   0.1 ,  -1.  ,  -4.5 ,   0.  ],
           [ 14.7 ,   0.15,  -1.  ,  -4.5 ,   0.  ]],

          [[ 14.8 ,   0.05,  -1.  ,  -4.5 ,   0.  ],
           [ 14.8 ,   0.1 ,  -1.  ,  -4.5 ,   0.  ],
           [ 14.8 ,   0.15,  -1.  ,  -4.5 ,   0.  ]],

          [[ 14.9 ,   0.05,  -1.  ,  -4.5 ,   0.  ],
           [ 14.9 ,   0.1 ,  -1.  ,  -4.5 ,   0.  ],
           [ 14.9 ,   0.15,  -1.  ,  -4.5 ,   0.  ]]],


         [[[ 13.

In [29]:
walkers[0:5]

array([[  1.76320754e+01,   3.37793888e-01,  -1.04721451e+00,
         -2.50662320e+00,   1.79962802e-02],
       [  1.76320754e+01,   3.37793888e-01,  -1.04721451e+00,
         -2.50662320e+00,   1.79962802e-02],
       [  1.76320754e+01,   3.37793888e-01,  -1.04721451e+00,
         -2.50662320e+00,   1.79962802e-02],
       [  1.76362425e+01,   3.37792462e-01,  -1.03994096e+00,
         -2.52785984e+00,  -5.10147351e-04],
       [  1.76356987e+01,   3.37786356e-01,  -1.03556775e+00,
         -2.51827828e+00,  -6.23745370e-03]])

In [30]:
temperatures = interp['temperature']([14.5,0.1,-0.3,-4.5,0.0])

In [31]:
temperatures

array([ 4.30977322])